# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(860, 550)
        mainWindow.setMinimumSize(QtCore.QSize(860, 550))
        mainWindow.setMaximumSize(QtCore.QSize(860, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("youtube logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("background-color: rgb(255, 67, 76);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 40, 540, 260))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Youtube-downloader.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lneUrl = QtWidgets.QLineEdit(self.centralwidget)
        self.lneUrl.setGeometry(QtCore.QRect(160, 320, 541, 31))
        self.lneUrl.setStyleSheet("background-color: rgb(254, 254, 254);")
        self.lneUrl.setObjectName("lneUrl")
        self.lneSaveTo = QtWidgets.QLineEdit(self.centralwidget)
        self.lneSaveTo.setGeometry(QtCore.QRect(160, 370, 541, 31))
        self.lneSaveTo.setStyleSheet("background-color: rgb(254, 254, 254);")
        self.lneSaveTo.setObjectName("lneSaveTo")
        self.btnDownload = QtWidgets.QPushButton(self.centralwidget)
        self.btnDownload.setGeometry(QtCore.QRect(160, 430, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDownload.setFont(font)
        self.btnDownload.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnDownload.setObjectName("btnDownload")
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(350, 430, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnClear.setFont(font)
        self.btnClear.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(540, 430, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnExit.setFont(font)
        self.btnExit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnExit.setObjectName("btnExit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 3px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.labell = QtWidgets.QLabel(self.centralwidget)
        self.labell.setGeometry(QtCore.QRect(30, 370, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labell.setFont(font)
        self.labell.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:3px;")
        self.labell.setAlignment(QtCore.Qt.AlignCenter)
        self.labell.setObjectName("labell")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setGeometry(QtCore.QRect(710, 370, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnBrowse.setFont(font)
        self.btnBrowse.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnBrowse.setObjectName("btnBrowse")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "YouTube Downloader"))
        self.btnDownload.setText(_translate("mainWindow", "Download"))
        self.btnClear.setText(_translate("mainWindow", "Clear"))
        self.btnExit.setText(_translate("mainWindow", "Exit"))
        self.label_2.setText(_translate("mainWindow", "Video Url:"))
        self.labell.setText(_translate("mainWindow", "Save To:"))
        self.btnBrowse.setText(_translate("mainWindow", "Browse"))
